# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://kbdxe.cn
date_format: "ordinal"
title: 狂奔的熊二
subtitle: "好好学习，天天向上"
description: "程立涛的个人博客"
keywords: 狂奔的熊二, chenglitao521
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 程立涛
organization:
organization_url:
github_username: chenglitao521
location: chengdu, China
email: chenglitao521@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
     href: /archives/
     label: 归档

 # -
 #   href: /wiki/
  #  label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: chenglita521/chenglitaoblog

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: chenglitao521
    repo: blog-comments
    oauth:
        client_id:
        client_secret:
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: chenglitao521
    repo: blog-comments
    clientID: 9358a497e74c1a17b6e6
    clientSecret: 48db6be665a0867b6f7dc2ebc5b398642d43d51a
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-118703491-1
